### ISSUE TITLE
RDS logger function

### ISSUE THREAD

**Issue by peppi001** [kkonradpl/xdr-gtk#1]
Hi!
First of all, this is a good software and Thank You.

It would be good an RDS logger function. For example 2-3 seconds skip the frequency and store RDS data to file.

THX
Peppi

PS: Sorry my pour english.

**Comment by kkonradpl** [comment]
This feature has been implemented as two separate functions in new version of xdr-gtk.
Scheduler tunes to each frequency defined in settings for a specified time.
Simple RDS logging stores all RDS data changes (PI, AF, PS, RT, PTY, ECC) to a file.
