### ISSUE TITLE
Wrong AF frequency tuned

### ISSUE THREAD

**Issue by andimik** [kkonradpl/xdr-gtk#15]
The AF part will not tune to the displayed frequency.

![grafik](https://github.com/kkonradpl/xdr-gtk/assets/24510556/ee7b8b8d-92c9-41f5-8478-d1bdd2e11217)

Clicking on 102.3 in the screenshot will tune to a wrong frequency:

```
write: T103175

```

![grafik](https://github.com/kkonradpl/xdr-gtk/assets/24510556/cdc14341-deef-46e7-85eb-be0362ee6f5b)

**Comment by kkonradpl** [comment]
Fixed in https://github.com/kkonradpl/xdr-gtk/commit/e750ec2911551ce578ffb1ea9ea762d5fd300b1b
