### ISSUE TITLE
Interval does not work

### ISSUE THREAD

**Issue by andimik** [kkonradpl/xdr-gtk#17]
setting an update interval does not work

![grafik](https://github.com/kkonradpl/xdr-gtk/assets/24510556/c75734e0-0927-417b-a17d-a25244501fda)

```
write: I1000,0
```

**Comment by HyperDX** [comment]
Custom interval is currently supported by XDR-I2C and FM-DX-Tuner.
Make sure to have the latest version uploaded on your board.

**Comment by kkonradpl** [comment]
This depends on the used firmware, as @HyperDX stated.

**Comment by kkonradpl** [comment]
This depends on the used firmware, as @HyperDX stated.
