### ISSUE TITLE
click on horizontal AFs won't change the frequency 

### ISSUE THREAD

**Issue by andimik** [kkonradpl/xdr-gtk#7]
Whenever the AF list is vertical, a click opens this alternative frequency.

![grafik](https://user-images.githubusercontent.com/24510556/219143156-6ac4694e-882c-4926-9216-34076db3db12.png)

But if you set `AF in horizontal list (restart required)` then a click just highlights the frequency but makes no difference:

![grafik](https://user-images.githubusercontent.com/24510556/219142506-d9289977-7055-4c93-b4c6-88ab9d7bcaa3.png)

**Comment by kkonradpl** [comment]
Fixed in master

**Comment by kkonradpl** [comment]
Please check with https://github.com/kkonradpl/xdr-gtk/commit/e750ec2911551ce578ffb1ea9ea762d5fd300b1b or latest version, should work OK.

**Comment by andimik** [comment]
I get an error at 100%:

```
[100%] Linking C executable xdr-gtk
/usr/bin/ld: CMakeFiles/xdr-gtk.dir/tuner.c.o: in function `tuner_rds_configure':
tuner.c:(.text+0x1066): undefined reference to `rdsparser_set_extended_check'
collect2: error: ld returned 1 exit status
make[2]: *** [src/CMakeFiles/xdr-gtk.dir/build.make:450: src/xdr-gtk] Fehler 1
make[1]: *** [CMakeFiles/Makefile2:185: src/CMakeFiles/xdr-gtk.dir/all] Fehler 2
```

**Comment by andimik** [comment]
Fixed the issue after `git pull --recurse-submodules` thanks to a hint on discord.

Horizontal AF is now clickable.
