### ISSUE TITLE
Success with MacOS build - with minor tweaks

### ISSUE THREAD

**Issue by lawendel** [kkonradpl/xdr-gtk#9]
Hi Konrad,

Also thanks to your previous support here I managed to successfully build xdr-gtk on MacOS M1 Monterey. I did encounter a few minor issues I want to share. 

1) tuner-conn.c in the src folder on GitHub has a non-compatible flag name: TCP_KEEPIDLE doesn't work on MacOS and generated an error during compilation. IT should be substituted with TCP_KEEPALIVE 

2) Compile option DCMAKE_INSTALL_PREFIX in build.sh sets the install prefix path as /usr, but that's a no-no with more recent MacOS versions. It gives place to a make install error because /usr/bin is set as read only. The default prefix is "usr/local", so this option should be omitted in the script.

Hope that helps, and thanks again

Andy

**Comment by kkonradpl** [comment]
Thanks for your report.

The first one issue was fixed in https://github.com/kkonradpl/xdr-gtk/commit/23e4fd58480fced36cbaf907e741ed68e9da8e2d
The second one in https://github.com/kkonradpl/xdr-gtk/commit/6acab75d28e2aabaa6405bdec8cb264d21e2b732
